version: "3"
services:
  web:
    image: nginx:stable
    volumes:
      - ./docker-nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/:/var/www/html
    ports:
      - 8004:80
    networks:
      backend:
  php:
    image: chialab/php:7.4-fpm
    volumes:
      - ${PWD}/:/var/www/html
    environment:
      DB_HOST: database
      DB_NAME: boxbilling
      DB_USER: root
      DB_PASS: root
    networks:
      backend:
    depends_on:
      - database
    restart: always
  database:
    image: mysql:5
    ports:
      - 3312:3306
    environment:
      MYSQL_ROOT_PASSWORD: masjack
    networks:
      backend:
    restart: always
networks:
  backend:
